"""Canonical document-level editorial treatment features for Format V2."""

from enum import Enum


class EditorialTreatmentFeature(str, Enum):
    """Describe how a document is organized independently of its Topic."""

    EVENT_REPORTING = "EVENT_REPORTING"
    TEMPORAL_MOVEMENT = "TEMPORAL_MOVEMENT"
    COMPLETED_OUTCOME = "COMPLETED_OUTCOME"
    CAUSAL_EXPLANATION = "CAUSAL_EXPLANATION"
    MECHANISM_EXPLANATION = "MECHANISM_EXPLANATION"
    ACTIONABLE_GUIDANCE = "ACTIONABLE_GUIDANCE"
    PROCEDURAL_SERVICE = "PROCEDURAL_SERVICE"
    CLAIM_VERIFICATION = "CLAIM_VERIFICATION"
    URGENT_BREAKING_SIGNAL = "URGENT_BREAKING_SIGNAL"
    LIST_OR_RANKING_STRUCTURE = "LIST_OR_RANKING_STRUCTURE"
    INTERVIEW_QA_STRUCTURE = "INTERVIEW_QA_STRUCTURE"
    OPINION_ARGUMENTATION = "OPINION_ARGUMENTATION"
    COMPARATIVE_STRUCTURE = "COMPARATIVE_STRUCTURE"
    NARRATIVE_SCENE_STRUCTURE = "NARRATIVE_SCENE_STRUCTURE"
    BIOGRAPHICAL_ARC = "BIOGRAPHICAL_ARC"
