"""Canonical symbolic warnings for editorial resolution."""

from enum import Enum


class EditorialResolutionWarning(str, Enum):
    """Expose safe resolver provenance without free-form provider payloads."""

    ADJUDICATION_AMBIGUITY_REMAINS = "ADJUDICATION_AMBIGUITY_REMAINS"
    FORMAT_FALLBACK_USED = "FORMAT_FALLBACK_USED"
    FORMAT_V1_V2_DISAGREEMENT = "FORMAT_V1_V2_DISAGREEMENT"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_CONFIGURATION_ERROR = "PROVIDER_CONFIGURATION_ERROR"
    PROVIDER_AUTHENTICATION_ERROR = "PROVIDER_AUTHENTICATION_ERROR"
    PROVIDER_PERMISSION_ERROR = "PROVIDER_PERMISSION_ERROR"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    INCOMPLETE_ADJUDICATION_RESPONSE = "INCOMPLETE_ADJUDICATION_RESPONSE"
    INVALID_ADJUDICATION_RESPONSE = "INVALID_ADJUDICATION_RESPONSE"
    FINGERPRINT_MISMATCH = "FINGERPRINT_MISMATCH"
    ILLEGAL_ADJUDICATED_CANDIDATE = "ILLEGAL_ADJUDICATED_CANDIDATE"
    FORMAT_STRUCTURE_INCOMPLETE = "FORMAT_STRUCTURE_INCOMPLETE"
    FORMAT_UNRESOLVED = "FORMAT_UNRESOLVED"
    TOPIC_UNRESOLVED = "TOPIC_UNRESOLVED"
    AUTHORITY_OBSERVATION_FAILED = "AUTHORITY_OBSERVATION_FAILED"
