"""Canonical limited Topic authority contract violations."""

from enum import Enum


class TopicAuthorityContractViolation(str, Enum):
    """Identify an unsafe applied-authority state."""

    AUTHORITY_APPLIED_IN_SHADOW_MODE = "AUTHORITY_APPLIED_IN_SHADOW_MODE"
    AUTHORITY_APPLIED_WITHOUT_ADJUDICATION = "AUTHORITY_APPLIED_WITHOUT_ADJUDICATION"
    AUTHORITY_APPLIED_WITH_REVIEW_REQUIRED = "AUTHORITY_APPLIED_WITH_REVIEW_REQUIRED"
    AUTHORITY_APPLIED_WITH_AMBIGUITY = "AUTHORITY_APPLIED_WITH_AMBIGUITY"
    AUTHORITY_APPLIED_WITH_LOW_CONFIDENCE = "AUTHORITY_APPLIED_WITH_LOW_CONFIDENCE"
    AUTHORITY_APPLIED_WITH_INVALID_RESPONSE = "AUTHORITY_APPLIED_WITH_INVALID_RESPONSE"
    AUTHORITY_APPLIED_WITH_INVALID_CANDIDATE = "AUTHORITY_APPLIED_WITH_INVALID_CANDIDATE"
    AUTHORITY_APPLIED_WITH_INVALID_FINGERPRINT = "AUTHORITY_APPLIED_WITH_INVALID_FINGERPRINT"
    AUTHORITY_APPLIED_WITH_PROVIDER_UNAVAILABLE = "AUTHORITY_APPLIED_WITH_PROVIDER_UNAVAILABLE"
    FORMAT_AUTHORITY_VIOLATION = "FORMAT_AUTHORITY_VIOLATION"
    READER_INTENT_AUTHORITY_VIOLATION = "READER_INTENT_AUTHORITY_VIOLATION"
