"""Canonical reasons that prevent limited Topic authority."""

from enum import Enum


class TopicAuthorityBlockReason(str, Enum):
    """Describe a specification-backed authority eligibility failure."""

    MODE_SHADOW = "MODE_SHADOW"
    TOPIC_ADJUDICATION_NOT_REQUESTED = "TOPIC_ADJUDICATION_NOT_REQUESTED"
    RESOLUTION_NOT_ADJUDICATED = "RESOLUTION_NOT_ADJUDICATED"
    SOURCE_NOT_ADJUDICATION = "SOURCE_NOT_ADJUDICATION"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    AMBIGUITY_REMAINS = "AMBIGUITY_REMAINS"
    PROVIDER_CONFIDENCE_TOO_LOW = "PROVIDER_CONFIDENCE_TOO_LOW"
    FINGERPRINT_INVALID = "FINGERPRINT_INVALID"
    CANDIDATE_INVALID = "CANDIDATE_INVALID"
    RESPONSE_INVALID = "RESPONSE_INVALID"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    NO_TOPIC_CHANGE = "NO_TOPIC_CHANGE"
