"""Supported compositional semantic relationship types."""

from enum import Enum


class SemanticRelationshipType(Enum):
    """Identify one reusable relationship between semantic components."""

    AUTHORITY_ACTS_ON_SUBJECT = "AUTHORITY_ACTS_ON_SUBJECT"
    ACTOR_PERFORMS_ACTION = "ACTOR_PERFORMS_ACTION"
    ACTION_TARGETS_OBJECT = "ACTION_TARGETS_OBJECT"
    METHOD_APPLIED_TO_SUBJECT = "METHOD_APPLIED_TO_SUBJECT"
    TOOL_USED_FOR_TASK = "TOOL_USED_FOR_TASK"
    EVENT_HAS_OUTCOME = "EVENT_HAS_OUTCOME"
    INDICATOR_DESCRIBES_DOMAIN = "INDICATOR_DESCRIBES_DOMAIN"
    SUBJECT_BELONGS_TO_DOMAIN = "SUBJECT_BELONGS_TO_DOMAIN"
    INSTITUTION_BELONGS_TO_DOMAIN = "INSTITUTION_BELONGS_TO_DOMAIN"
    RECOMMENDATION_TARGETS_AUDIENCE = "RECOMMENDATION_TARGETS_AUDIENCE"
    REQUIREMENT_APPLIES_TO_AUDIENCE = "REQUIREMENT_APPLIES_TO_AUDIENCE"
    ACTION_HAS_DEADLINE = "ACTION_HAS_DEADLINE"
    CLAIM_ATTRIBUTED_TO_AUTHORITY = "CLAIM_ATTRIBUTED_TO_AUTHORITY"
    PREDICTION_ABOUT_EVENT = "PREDICTION_ABOUT_EVENT"
    INTERPRETATION_OF_INDICATOR = "INTERPRETATION_OF_INDICATOR"
    CONSEQUENCE_OF_EVENT = "CONSEQUENCE_OF_EVENT"
    OWNER_CONTROLS_OBJECT = "OWNER_CONTROLS_OBJECT"
    SOURCE_REPORTS_EVENT = "SOURCE_REPORTS_EVENT"
    EVENT_ORGANIZES_SUBJECT = "EVENT_ORGANIZES_SUBJECT"
