"""Supported editorial content type values."""

from enum import Enum


class ContentType(str, Enum):
    """Describe the editorial treatment assigned to source material."""

    BREAKING_NEWS = "BREAKING_NEWS"
    STANDARD_NEWS = "STANDARD_NEWS"
    NEWS_REWRITE = "NEWS_REWRITE"
    PUBLIC_SERVICE_NEWS = "PUBLIC_SERVICE_NEWS"
    GOVERNMENT_SERVICE_CONTENT = "GOVERNMENT_SERVICE_CONTENT"
    EXPLAINER = "EXPLAINER"
    FACT_CHECK = "FACT_CHECK"
    HEALTH_CONTENT = "HEALTH_CONTENT"
    LEGAL_FINANCIAL_HIGH_RISK_CONTENT = (
        "LEGAL_FINANCIAL_HIGH_RISK_CONTENT"
    )
    SPORTS_NEWS = "SPORTS_NEWS"
    TECHNOLOGY_NEWS = "TECHNOLOGY_NEWS"
    ECONOMY_NEWS = "ECONOMY_NEWS"
    TRENDING_SOCIAL_CLAIM = "TRENDING_SOCIAL_CLAIM"
